### PR TITLE
Fix variable typo

### PR DESCRIPTION
**Pull request by arski**
-nt

### CODE REVIEW

**Comment by arski** [comment]
🤷

**Comment by janetst** [comment]
This is still an issue, as far as I can tell.

**Comment by arski** [comment]
yes but nobody is reviewing it.. ill give it till the end of the week, then feel free to open your own copy of this PR :)

**Comment by janetst** [comment]
Please leave open until the end of the year. We are a tad bit busy with reInvent updates, but after that we plan to update and refresh the docs on GitHub.

**Pull request merged**
