### PR TITLE
Fix ARN in Principal block

### PR DESCRIPTION
**Pull request by pradeepbhadani**
*Issue #, if available:*

*Description of changes:*
Fix `grantee-account-id` ARN in Principal block

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pradeepbhadani** [comment]
@janetst
@prazmaap
@Dlozitskiy

**Comment by janetst** [comment]
Thank you for telling us about this issue. I am fixing this issue in our source repository, and will update the content here when time permits.

**Comment by pradeepbhadani** [comment]
@janetst  Which source repository you are referring? Shall I raise this change in another repository as well?

**Comment by janetst** [comment]
No, we make the changes in our internal repository and then sync it with the content on GitHub. The change will appear first in the public docs, and then later, here on GitHub.,

**Pull request merged**
